version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do contêiner para a porta 3000 local
    volumes:
      - .:/app # Mapeia os arquivos do projeto local para o contêiner
      - /app/node_modules # Ignora os node_modules locais
    environment:
      - NODE_ENV=production # Define a variável de ambiente como produção
    container_name: nextjs_app # Dá um nome ao contêiner